# Generated by Django 5.0.7 on 2024-08-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
