# Generated by Django 5.0.7 on 2024-08-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_genre_genre_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
