name: Django CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15  
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456 
          POSTGRES_DB: Movie 
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up the database
      run: |
        cd movie_site
        python manage.py migrate

    - name: Run tests
      run: |
        cd movie_site
        python manage.py test

    - name: Generate coverage report
      run: |
        pip install coverage
        cd movie_site
        coverage run manage.py test
        coverage report
        coverage xml
        
    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: movie_site/coverage.xml
